name: Devcontainer CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Stonefish Install
        id: cache-stonefish
        uses: actions/cache@v3
        with:
          path: ros2_ws/install/stonefish_vendor
          key: stonefish-lib-${{ hashFiles('third_party/stonefish/**') }}

      - name: Build and Test in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            source /opt/ros/jazzy/setup.bash
            
            cd ros2_ws

            sudo chown -R $(whoami) install/ || true

            if [ -f "install/stonefish_vendor/lib/libStonefish.so" ]; then
                echo "Cache Hit: Stonefish library found."
                echo "Skipping stonefish_vendor compilation..."
                
                source install/setup.bash
                
                SKIP_ARG="--packages-skip stonefish_vendor"
            else
                echo "Cache Miss: Building Stonefish from scratch..."
                
                colcon build --packages-select stonefish_vendor
                
                source install/setup.bash
                SKIP_ARG=""
            fi

            echo "Building workspace..."
            colcon build $SKIP_ARG
